name: Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

    deploy:
    
      
        name: Setup Gcloud Account
        runs-on: ubuntu-latest
        env:
          IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }}
        steps:
        
        - name: Auth
          id: 'auth'
          uses: 'google-github-actions/auth@v0'
          with:
            service_account: githubactions@buoyant-set-297200.iam.gserviceaccount.com
            credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
   
        - name: Get Secret Manager secrets
          id: 'secrets'
          uses: google-github-actions/get-secretmanager-secrets@v0
          with:
            secrets: |-
              GCP_PROJECT_ID:projects/502135548825/secrets/GCP_PROJECT_ID/versions/1
            
        - name: Configure Docker
          run: gcloud auth configure-docker --account 'githubactions@buoyant-set-297200.iam.gserviceaccount.com'
            
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Build Docker image
          run: docker build . -t $IMAGE_NAME 



        - name: Push Docker image
          run: docker push $IMAGE_NAME

        - name: Deploy Docker image
          run:  gcloud run deploy ${{ secrets.GCP_APP_NAME }} --region us-central1 --image gcr.io/${{ steps.secrets.outputs.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }} --platform managed --allow-unauthenticated --project ${{ steps.secrets.outputs.GCP_PROJECT_ID }}
