name: Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

    deploy:
    
      
        name: Setup Gcloud Account
        runs-on: ubuntu-latest
        env:
          IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }}
          
        steps:
          
            
        - name: Configure Docker
          run: gcloud auth configure-docker --quiet
            
        - name: Checkout repository
          uses: actions/checkout@v2
          
        - name: Auth
          id: 'auth'
          uses: 'google-github-actions/auth@v0'
          with:
            credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
            project_id: '${{ secrets.GCP_PROJECT_ID }}'
            service_account: '${{ secrets.GCP_EMAIL }}'
            
        - name: Get Secret Manager secrets
          id: 'secrets'
          uses: google-github-actions/get-secretmanager-secrets@v0.3.1
          with:
            secrets: |-
              GCP_APP_NAME:projects/502135548825/secrets/GCP_APP_NAME/versions/1
              GCP_PROJECT_ID:projects/502135548825/secrets/GCP_PROJECT_ID/versions/1

        - name: Build Docker image
          run: docker build . -t $IMAGE_NAME 


        - name: Push Docker image
          run: docker push $IMAGE_NAME 

        - name: Deploy Docker image
          run:  gcloud run deploy ${{ steps.secrets.outputs.GCP_APP_NAME }} --region us-central1 --image gcr.io/${{ steps.secrets.outputs.GCP_PROJECT_ID }}/${{ steps.secrets.outputs.GCP_APP_NAME }} --platform managed --allow-unauthenticated --project ${{ steps.secrets.outputs.GCP_PROJECT_ID }}
