name: Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

    deploy:
    
      
        name: Setup Gcloud Account
        runs-on: ubuntu-latest
        env:
          IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }}
        steps:
        
        - name: Auth
          id: 'auth'
          uses: 'google-github-actions/auth@v0'
          with:
            credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
            
        - name: Get Secret Manager secrets
          id: 'secrets'
          uses: google-github-actions/get-secretmanager-secrets@v0.3.1
          with:
            secrets: |-
              GCP_EMAIL:projects/502135548825/secrets/GCP_EMAIL/versions/1
              GCP_CREDENTIALS:projects/502135548825/secrets/GCP_CREDENTIALS/versions/1
            
        - name: Login
          uses: google-github-actions/setup-gcloud@master
          with:
            GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
            service_account_email: ${{ steps.secrets.outputs.GCP_EMAIL }}
            service_account_key: ${{ steps.secrets.outputs.GCP_CREDENTIALS }}
            
            
        - name: Configure Docker
          run: gcloud auth configure-docker --quiet
            
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Build Docker image
          run: docker build . -t $IMAGE_NAME 



        - name: Push Docker image
          run: docker push $IMAGE_NAME

        - name: Deploy Docker image
          run:  gcloud run deploy ${{ secrets.GCP_APP_NAME }} --region us-central1 --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }} --platform managed --allow-unauthenticated --project ${{ secrets.GCP_PROJECT_ID }}
